CREATE TABLE IF NOT EXISTS usuario (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    senha VARCHAR(100) NOT NULL,
    telefone CHAR(11) NOT NULL UNIQUE,
    dtNascimento DATE NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    CONSTRAINT tipoChk CHECK (tipo IN ('Beneficiario', 'Cliente'))
);

INSERT INTO usuario VALUES (DEFAULT, 'adm', 'adm', 'adm', '00000000000', '2000-01-01', 'Beneficiario');